"""empty message

Revision ID: 322ab5249404
Revises: 1bb181a9c216
Create Date: 2025-01-31 09:45:07.745131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322ab5249404'
down_revision: Union[str, None] = '1bb181a9c216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_likes_ibfk_1', 'comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_likes', 'comments', ['content_id'], ['comment_id'], ondelete='CASCADE')
    op.drop_constraint('post_likes_ibfk_1', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'posts', ['content_id'], ['post_id'], ondelete='CASCADE')
    op.drop_constraint('story_likes_ibfk_1', 'story_likes', type_='foreignkey')
    op.create_foreign_key(None, 'story_likes', 'stories', ['content_id'], ['story_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_likes', type_='foreignkey')
    op.create_foreign_key('story_likes_ibfk_1', 'story_likes', 'stories', ['content_id'], ['story_id'])
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_ibfk_1', 'post_likes', 'posts', ['content_id'], ['post_id'])
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.create_foreign_key('comment_likes_ibfk_1', 'comment_likes', 'comments', ['content_id'], ['comment_id'])
    # ### end Alembic commands ###
