"""location model create

Revision ID: e5c3b8991c39
Revises: 25dda1508ba7
Create Date: 2025-01-24 14:24:06.129520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c3b8991c39'
down_revision: Union[str, None] = 'c7b13a1ab89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_tags',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('citation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_tags_location_id'), 'location_tags', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_tags_location_id'), table_name='location_tags')
    op.drop_table('location_tags')
    # ### end Alembic commands ###

